### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by motephyr**
fix readme

### CODE REVIEW

**Comment by motephyr** [comment]
I spent a lot of time and get this error:
```
NoMethodError (undefined method `resource_owner_from_assertion' for #<Doorkeeper::TokensController:0x00000006a34f98>)
```

and the reason is i use 
```
gem 'doorkeeper-grants_assertion'
```

but i found i lost railtie.rb, and the file contain also different.

so i do this
```
gem 'doorkeeper-grants_assertion' , git: 'https://github.com/doorkeeper-gem/doorkeeper-grants_assertion.git'
```

it works. and take out my 5 hours.

**Comment by NuckChorris** [comment]
I don't believe this gem is released to Rubygems yet

**Comment by motephyr** [comment]
but Rubygems's version is old.

**Comment by Charizard** [comment]
:+1: for saving my time. I think the latest master needs to be released in ruby gems.

**Comment by NuckChorris** [comment]
This gem is not release ready. If you want to use it right now, use:

```ruby
gem 'doorkeeper-grants_assertion', github: 'doorkeeper-gem/doorkeeper-grants_assertion'
```

But let's be clear that this is prerelease software and it's absolutely not ready for production.

**Comment by tute** [comment]
@NuckChorris https://github.com/doorkeeper-gem/doorkeeper-grants_assertion/pull/14#issuecomment-166375513 explains how it should be added. This PR is no better. Until it is released as v1, it won't be in rubygems. Thank you!

**Pull request closed without merging**
