### PR TITLE
include Doorkeeper::GrantsAssertion in Doorkeeper::Helpers::Controller

### PR DESCRIPTION
**Pull request by buszu**
I've changed railtie to fix error below.
```
NoMethodError (undefined method `resource_owner_from_assertion' for #<Doorkeeper::TokensController:0x007ff48fcb9ce8>)
```

### CODE REVIEW

**Comment by kurtisnelson** [comment]
Still seeing this issue, going to point my gemfile at this repo

**Comment by buszu** [comment]
According to https://github.com/doorkeeper-gem/doorkeeper-grants_assertion/pull/4#issuecomment-55229546 I've just tried (and accidentally submitted https://github.com/doorkeeper-gem/doorkeeper-grants_assertion/pull/8) but don't get it atm (and I can hardly spend more time on it).

**Comment by tute** [comment]
Thanks @buszu! The fix is already there now (https://github.com/doorkeeper-gem/doorkeeper-grants_assertion/commit/1b3acee3437fef80dd95038d40a1739aecdab0c0), but no specs whatsoever.

**Comment by mandrews** [comment]
:+1:

**Comment by tute** [comment]
Travis CI just merged in, courtesy of @NuckChorris. Would you rebase this PR on top of latest master please? Thank you!

**Comment by NuckChorris** [comment]
@tute Is there a specific task this needs before closure if the fix is already merged in 1b3acee3437fef80dd95038d40a1739aecdab0c0?

**Comment by tute** [comment]
It's surprising it still shows the diff. I guess it's in. Thanks!

**Pull request closed without merging**
