### PR TITLE
Doorkeeper 4.0.0 compatible release, tested against Rails 4.2 and Rails 5.0

### PR DESCRIPTION
**Pull request by levent**
Builds on https://github.com/doorkeeper-gem/doorkeeper-grants_assertion/pull/21 against official doorkeeper 4 release.

### CODE REVIEW

**Comment by matfiz** [comment]
Looks great for me, thank you @levent. @NuckChorris, any remarks?

**Comment by NuckChorris** [comment]
Looks good, though it leaves in ruby 2.0 — is there any reason to continue supporting it when it's no longer developed?

**Comment by levent** [comment]
@NuckChorris am happy to pull out of ```.travis.yml``` or submit another pull request later on. I believe Ruby 2.0 is tested against but there's no specific logic targeting that version in the lib itself?

**Comment by NuckChorris** [comment]
It seems logical to drop support for versions of Ruby that won't receive updates anymore, namely 2.1 and lower.

That said, I think that's a different issue, I just happened to notice when I was reviewing the patchset here

**Comment by bolshakov** [comment]
Would you mind to release new version?

**Pull request merged**
